### ISSUE TITLE
fix broken links on docs

### ISSUE THREAD

**Issue by chopan123** [soroswap/docs#19]

**Comment by chopan123** [comment]
en la [documentacion](https://docs.soroswap.finance/01-concepts/04-advanced-topics/01-fees#protocol-charge-calculation) de soroswap al clickear sobre ciertos conceptos redirige a un repositorio vacío, para el ejemplo redirige a https://github.com/soroswap/docs/blob/main/old_docusaurus/docs/reference/smart-contracts/factory/README.md#feeto

**Comment by MattPoblete** [comment]
**Links dañados:**
- /:
    - Protocol Overview.
- /01-concepts:
    - /01-protocol-overview
        - /01-how-soroswap-works
            - Soroban. ⚠️ (Soroban docs)
        - /03-smart-contracts:
            - Periphery link. ⚠️
            - Factory Reference documentation.
            - Pairs Reference documentation.
            - Periphery Source code. ⚠️
            - Library Reference documentation.
            - Router Reference documentation.
        - /04-glossary:
            - Token Interface. ⚠️ (Soroban docs)
    - /02-design-decisions:
        - Whitepater.
        - FlashSwaps.
        - MINIMUM_LIQUIDITY.
        - totalSupply.
    - /03-core-concepts:
        - /01-swaps:
            - Protocol overview.
            - constant product formula.
            - whitepaper.
            - Flash Swaps.
            - Trading from a smart contract.
            - Trading(SDK).
        - /02-pools:
            - Understanding returns.
            - Fees.
            - Providing Liquidity.
        - /03-flash-swaps:
            - Using Flash Swaps.
        - /04-oracles:
            - whitepaper.
            - security audit section on Oracle Integrity.
            - building an Oracle.
    - /04-advanced-topics:
        - /01-fees:
            - LP returns.
            - feeTo.
            - whitepaper.
        - /02-pricing:
            - Protocol Overview.
            - constant product formula.
            - library.
            - router.
            - native V2 oracles.
            - getAmountsOut.
            - getOutputAmount.
            - minimumAmountOut.
            - getAmountsIn.
            - getInputAmount.
            - maximumAmountIn.
        - /04-security:
            - Read the report.
            - Pair.
            - Router.
            - Library.
            - Oracles
- /03-thecnical-reference:
    - Tutorials.⚠️
    - /06-soroswap-vs-uniswapv2:
        - /01-soroswappair-comparison:
            - https://rskswap.com/audit.html
            - overflow check.
            - remarks (**A note on arithmetic operations and data types:**).
    - /aggregator:
        - /03-comet.⚠️
- /05-tutorial:
    - /summary
        - /02-swap-stellar-classic-assets:
            - Doing Swap.
